server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true  # 开启JSP热加载
        checkInterval: 0   # 实时检查更新
    context-path: /car_rental

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_rental?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  mvc:
    view:
      prefix: /WEB-INF/view/system/
      suffix: .jsp
    static-path-pattern: /**  # 公开资源访问路径

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wn.carrentalplatform.model
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: org.apache.ibatis.type.LocalDateTimeTypeHandler

# PageHelper 配置
pagehelper:
  helper-dialect: mysql       # 指定数据库类型
  reasonable: true           # 启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  support-methods-arguments: true  # 支持通过Mapper接口参数来传递分页参数
  params: count=countSql     # 支持通过Mapper接口参数来传递分页参数
  page-size-zero: true      # 当设置为true的时候，如果pagesize设置为0就不执行分页

# 添加文件上传路径配置
upload:
  path: D:/upload  # Windows路径示例
  # path: /Users/your-username/upload  # Mac/Linux路径示例