server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true  # 开启JSP热加载
        checkInterval: 0   # 实时检查更新
    context-path: /car_rental

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_rental?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  mvc:
    view:
      prefix: /WEB-INF/view/system/
      suffix: .jsp
    static-path-pattern: /**  # 公开资源访问路径

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wn.carrentalplatform.model
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: org.apache.ibatis.type.LocalDateTimeTypeHandler 