spring:
  application:
    name: tlias-web-management
  #mysql连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 12345678
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 100MB
      #最大请求体总大小
      max-request-size: 100MB
  jackson:
    serialization:
      fail-on-empty-beans: false


#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启了驼峰命名开关
    map-underscore-to-camel-case: true

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#文件上传
#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-tlias-chinhae
    region: cn-beijing